[package]
name = "icann-rdap-common"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = """
Common RDAP data structures.
"""
rust-version.workspace = true

[dependencies]
chrono.workspace = true
cidr.workspace = true
const_format.workspace = true
buildstructor.workspace = true
idna.workspace = true
ipnet.workspace = true
prefix-trie.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
thiserror.workspace = true

[features]
default = []
iana_registry_tests = []

[dev-dependencies]

indoc.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
rstest.workspace = true
